# Database connection, MariaDB and MYSQL supported, no sqllite
Database: "jdbc:mariadb://0.0.0.0:3306/Database"
Username: ""
Password: ""

AdminPermission: telepads.admin

# Command settings
PortableTelepad:
  permission: "telepads.commands.portabletelepad"
  aliases:
    - pad
GiveBuildItem:
  permission: "telepads.commands.givetlelepaditem"
  aliases:
    - giveteleitem
ReloadCommand:
  permission: "telepads.commands.reload"

Messages:
  noPerms: "<red>Du hast keine Berechtigungen auf dieses Telepad.</red>"
  noMoney: "<red>Du hast nicht genug Geld.</red>"
  dbError: <red>Es gab einen Fehler beim erstellen des Telepads in der Datenbank, bitte kontactiere einen Administrator!</red>"
  createTelepad: "<green>Dein Telepad wurde erstellt.</green>"
  telepadLevelRequired: "<red>Telepad level 2 benötigt!</red>"
  setDestination: "Lege das Ziel fest."
  regex: "<red>Dieser Name ist ungültig <br>Der Name darf nur die Zeichen [a-zA-Z0-9_ </>] verwenden <br> und muss zwischen 3 und 32 Zeichen lang sein.</red>"
  invFull: "<red>Dein Inventar ist voll, bitte lerre es um das Telepad aufzusammeln</red>"
  pickup: "<green>Du hast das Telepad erfolgreich augehoben.</green>"
  exitChatInput: "Abgebrochen"
  upgraded: "Dein Telepad wurde aufgewertet."
  # Placeholder: <cost>
  teleport: "Dir wurden <cost> zum Teleport abgezogen."
  upgrade: "Das Aufwerten kostet <cost> Coins."
  pickupRegainMoney: "Dir wurden <green>200 Coins</green> gutgeschrieben."
  # Placeholder: <name>
  renameTelepad: "Dein Telepad wurde \"<name>\" genannt."
  fullInventory: "<red>Dein Inventar ist voll, bitte lerre es um das Telepad aufzusammeln</red>"
  pickup: "<green>Du hast das Telepad erfolgreich augehoben.</green>"
  levelup: "Dein Telepad wurde aufgewertet."
  addPermission: "Der Spieler \"<green><name></green>\" wurde für dieses Telepad gesetzt."
  removePermission: ""
  blocknotFound: "<red>Dieser Block wurde nicht gefunden.</red>"
  changesBlock: "Dein Telepad Block wurde zu \"<green><name></green>\" geändert."
  # This ussually happens when a telepad is right klicked which is not in the databse (example: DB reset, )
  errorSupport: "Ein fehler ist aufgetreten, bitte melde dich im support."
  # Placeholder: <desti>
  setDestination: "Du hast \"<desti>\" erfolgreich als Ziel gesetzt."

UseTelepadCost: 2
CommonPage:
  continue: "Weiter"
  back: "Zurück"
  close: "Schließen"
  public: "Öffendlich"
  private: "Privat"
TelepadGUI:
  pickup:
    name: "Aufheben"
    block: "red_dye"
  levelup:
    name: "Aufwerten"
    block: "emerald" 
    cost: 200
  customizer:
    name: "Anpassungen"
    block: "anvil"
    lore: "Name und Anzeige Block"
    blocktype:
      name: "Anzeige Block"
      question: "Welcher soll dein neuer Anzeige Block sein?.<br>Schreibe \"exit\" oder \"abbrechen\" um den Vorgang abzubrechen."
      exitWords:
        - "exit"
        - "abbrechen"
    telepadname:
      name: "Klicken zum Namen ändern."
      block: "NAME_TAG"
      question: "Wie möchtest du dein Telepad nennen?.<br>Schreibe \"exit\" oder \"abbrechen\" um den Vorgang abzubrechen."
      exitWords:
        - "exit"
        - "abbrechen"
  destination:
    name: "Ziel"
    block: "grass_block"
  publicity:
    name: "Sichtbarkeit"
    block: "ENDER_EYE"
    list:
      name: "Spieler Liste"
      block: "paper"
      removePlayer:
        name: "Klicke um zu entfernen."
    add:
      name: "Spieler hinzufügen"
      block: "player_head"
      question: "Schreibe den Spielernamne den du hinzufügen willst in den Chat.<br>Schreibe \"exit\" zum abzubrechen."
      exitWords:
        - exit
        - abbrechen
PortableTelepad:
  LeftClickTELEPRT: "<white>Links Klick: Teleport</white>"
  RightClickFAVOTITE: "<white>Rechts Klick: Favorisieren</white>"
  FavoriteMarker: "<yellow>Favorit</yellow>"  
  